stages:
  - build
  - test
  - package
  - publish

variables:
  MAVEN_CLI_OPTS: "-B -V"

cache:
  paths:
    - .m2/repository/
    - frontend/node_modules/

build:
  stage: build
  image: node:18-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/
